version: '3.6'

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16

services:
  postgres:
    image: postgres:12
    pull_policy: always
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      internal:
        aliases:
          - database
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    environment:
      - ADMINER_DESIGN='nette'
    ports:
      - 8888:8080
    restart: always
    networks:
      - internal

volumes:
  pg-data:
    name: pg-data
    # external: true